CREATE TABLE rides(
    ride_id VARCHAR(5) PRIMARY KEY UNIQUE NOT NULL,
    ride_name VARCHAR(50) NOT NULL,
    riders varchar (150) NOT NULL,
    restrictions varchar (1000) NOT NULL,
    fast_pass varchar (4) NOT NULL
);

/** RIDES TABLE - FOR RIDE ID GO TO 2017 MAGIC KINGDOM MAP. ID # HAS CHANGED -EM**/
INSERT INTO rides
(ride_id, ride_name, riders, restrictions, fast_pass)
VALUES
("MK16", "The Magic Carpets of Aladdin", "2-4", "No height or age restrictions", "Yes"),
("MK17", "Jungle Cruise", "10 boats which carry approx. 20 passengers each", "No height or age restrictions", "Yes"),
("MK18", "Enchanted Tiki Room", "Not applicable, seated attraction", "No height or age restrictions", "No"),
("MK19", "Pirates of the Caribbean", "Up to 23 adults per boat, spread over 6 rows", "No height or age restrictions", "Yes"),
("MK26", "Splash Mountain", "6 riders per boat", "No height or age restrictions", "Yes"),
("MK28", "Big Thunder Mountain Railroad", "30 per train, 15 pairs of two per car", "40 inches or taller", "Yes"),
("MK30", "Country Bear Jamboree", "Not applicable, seated attraction", "No height or age restrictions", "No")
("MK38", "Haunted Mansion", "2-3", "No height or age restrictions", "Yes"),
("MK43", "Prince Charming Regal Carrousel", "1", "No height or age restrictions", "No"),
("MK44", "Mickey's PhilharMagic", "Not applicable, seated attraction", "No height or age restrictions", "Yes"),
("MK45", "Peter Pan's Flight", "2-4", "No height or age restrictions", "Yes"),
("MK46", "It's A Small World", "approx. 20", "No height or age restrictions", "Yes"),
("MK47", "Enchanted Tales with Belle", "Not applicable", "No height or age restrictions", "Yes"),
("MK48", "Under the Sea - Journey of The Little Mermaid", "2-3", "No height or age restrictions", "Yes"),
("MK51", "Walt Disney World Railroad", "", "No height or age restrictions", "No"),
("MK53", "The Barnstormer", "2-4", "35 inches or taller", "Yes"),
("MK54", "Dumbo the Flying Elephant", "1-2", "No height or age restrictions", "Yes"),
("MK55", "Mad Tea Party", "1-5", "No height or age restrictions", "Yes"),
("MK57", "The Many Adventures of Winnie the Pooh", "4-6", "No height or age restrictions", "Yes"),
("MK58", "Seven Dwarfs Mine Train", "2-4", "38 inches or taller", "Yes"),
("MK72", "Stitches Great Escape", "", "", "No"),
("MK73", "Tomorrowland Speedway", "", "", "Yes"),
("MK74", "Space Mountain", "", "", "Yes"),
("MK75", "Astro Orbiter", "", "", "No"),
("MK77", "Carousel of Progress", "", "", "Yes"),
("MK78", "Buzz Lightyear's Space Ranger Spin", "", "", "Yes"),
("EP1", "Spaceship Earth", "", "", "No"),
("EP4", "Mission: SPACE", "", "", "No"),
("EP6", "Test Track", "", "", "No"),
("EP24", "The Sea with Nemo and Friends", "", "", "No"),
("EP26", "Soarin", "", "", "No"),
("EP27", "Living with the Land"),
("EP29", "Journey Into the Imagination with Figment", "", "", "No"),
("EP58", "Grand Fiesta Tour Starring the Three Caballeros", "", "", "No"),
("EP63", "Frozen Ever After", "", "", "No"),
("HS1", "The Great Movie Ride", "", "", "No"),
("HS13", "Star Tours the Adventure Continues", "", "", "No"),
("HS29", "Toy Story Mania", "", "", "No"),
("HS32", "Voyage of the Little Mermaid", "", "", "No"),
("HS36", "Rock n' Roller Coaster", "", "", "No"),
("HS37", "The Hollywood Tower of Terror", "", "", "No"),
("AK21", "Kilimanjaro Safaris", "", "", "No"),
("AK34", "Kali River Rapids", "", "", "No"),
("AK35", "Expedition Everest", "", "", "No"),
("AK50", "Primeval Whirl", "", "", "No"),
("AK51", "TriceraTop Spin", "", "", "No"),
("AK52", "DINOSAUR", "", "", "No");
